CREATE VIEW v_centers as SELECT ecenter.centerId as center_id, ecenter.centerName as center_name, ecenter.barangay,ecenter.centerAddress as center_address,(select concat(eworkers.fName,' ', eworkers.mName ,' ', eworkers.lName ,' ', eworkers.ext) from eworkers WHERE eworkers.centerId = ecenter.centerId) as worker_name from ecenter;

CREATE VIEW v_eccd_students AS SELECT pupilsId as student_id,concat(`epupils`.`lName`,', ',`epupils`.`fName`,' ',`epupils`.`mName`,' ',`epupils`.`ext`) AS `student_name`, epupils.gender,(select max(date_weighing) from e_weighing WHERE e_weighing.student_id = epupils.pupilsId) as max_weighing,(select height FROM e_weighing WHERE e_weighing.student_id = epupils.pupilsId and e_weighing.date_weighing = max_weighing) as height,(select weight FROM e_weighing WHERE e_weighing.student_id = epupils.pupilsId and e_weighing.date_weighing = max_weighing) as weight,(select  wfa FROM e_weighing WHERE e_weighing.student_id = epupils.pupilsId and e_weighing.date_weighing = max_weighing) as wfa,(select hfa FROM e_weighing WHERE e_weighing.student_id = epupils.pupilsId and e_weighing.date_weighing = max_weighing) as hfa,(select wfh FROM e_weighing WHERE e_weighing.student_id = epupils.pupilsId and e_weighing.date_weighing = max_weighing) as wfh from epupils;

 CREATE VIEW v_20days AS SELECT s.student_id,s.center_id,s.worker_id,s.student_name,s.gender,(select w.id FROM e_weighing w WHERE w.student_id =s.student_id and w.date_weighing = (SELECT DATE_ADD(date_weighing, INTERVAL 20 DAY) FROM e_weighing t2 WHERE t2.student_id = t2.student_id ORDER BY T2.date_weighing ASC limit 1) ORDER BY w.date_weighing LIMIT 1) as weighing_id,s.year_id FROM `center_students_schoolyear` `s`;

 CREATE VIEW v_40days AS SELECT s.student_id,s.center_id,s.worker_id,s.student_name,s.gender,(select w.id FROM e_weighing w WHERE w.student_id =s.student_id and w.date_weighing = (SELECT DATE_ADD(date_weighing, INTERVAL 40 DAY) FROM e_weighing t2 WHERE t2.student_id = t2.student_id ORDER BY T2.date_weighing ASC limit 1) ORDER BY w.date_weighing LIMIT 1) as weighing_id,s.year_id FROM `center_students_schoolyear` `s`;

 CREATE VIEW v_uponentry as SELECT s.student_id,s.center_id,s.worker_id,s.student_name,s.gender,(select T1.id from e_weighing T1 WHERE T1.date_weighing = (select MIN(T2.date_weighing) FROM e_weighing T2 WHERE T2.student_id = s.student_id)) as weighing_id,s.year_id FROM `center_students_schoolyear` `s`;

 CREATE VIEW v_terminal as SELECT s.student_id,s.center_id,s.worker_id,s.student_name,s.gender,(select T1.id from e_weighing T1 WHERE T1.date_weighing = (select MAX(T2.date_weighing) FROM e_weighing T2 WHERE T2.student_id = s.student_id)) as weighing_id,s.year_id FROM `center_students_schoolyear` `s`;

CREATE VIEW v_weighing as SELECT w.*,CONCAT(p.lName,', ',p.fName,' ',p.mName,' ',p.ext) as student_name FROM e_weighing w LEFT JOIN epupils p ON p.pupilsId = w.student_id WHERE date_weighing = (select MAX(date_weighing) FROM e_weighing w2 WHERE w.student_id = w2.student_id);
-- SELECT s.student_id,s.center_id,s.worker_id,s.student_name,w.id as weighing_id,w.date_weighing,w.weight,w.height,w.wfa,w.hfa,w.wfh,w.status as health_status FROM `center_students_schoolyear` `s` LEFT JOIN e_weighing w on w.student_id = s.student_id;
